name: Android Tests

on:
  pull_request:
    branches: 
      - '*'
    types: opened
  issue_comment:
    branches: 
      - '*'
    types: created

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: 'test-this-please'
          reaction: '+1'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: current path
        run: pwd
      - name: Run tests
        run: ./.github/scripts/test_app.sh
        if: steps.check.outputs.triggered == 'true'
        
  #test:
    #needs: deploy
    #if: "needs.deploy.steps.check.outputs.triggered == 'true'"
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    #steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #- uses: actions/checkout@v2

    # Runs a single command using the runners shell
    #- name: Run script
     # run: sh .github/scripts/test_app.sh
    #- name: Echooo
     # run: echo 'echo corrio linea $COMMENT_FOUND'
     # if: $COMMENT_FOUND == 'true'
      
