name: Android On Demand Tests

on:
  pull_request:
    branches: 
      - '*'
    types: opened
  issue_comment:
    branches: 
      - '*'
    types: created

jobs:
  deploy:
    runs-on: macOS-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: 'test-this-please'
          reaction: '+1'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - uses: actions/checkout@v2
        
      - name: Fastlane install 
        run: brew install fastlane
        
      - name: Bundle Install
        run: bundle install 

      - name: Run tests
        # run: sh .github/scripts/test_app.sh
        run: bundle exec fastlane github_build
        if: steps.check.outputs.triggered == 'true'
      
