name: Android Create QC Release

on:
  push:
    branches: 
     - develop

jobs: 
  apk:
    name: Generate APK
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Fastlane install 
        run: brew install fastlane
        
      - name: Bundle Install
        run: bundle install
         
      - name: Give permissions
        run: sh .github/scripts/give_permissions_gradle.sh
        
      - name: Run tests
        run: bundle exec fastlane github_build
