name: Android Create QC Release

on:
  push:
    branches: 
     - develop

jobs:
  
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
    
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Unit tests
      run: bash ./gradlew test --stacktrace
      
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Store APK
        uses: actions/upload-artifact@v1
        with:
            name: app
            path: app/build/outputs/apk/debug/app-debug.apk
      - name: Deploy to App Center
        uses: wzieba/AppCenter-Github-Action@v1.0.0
        with:
          appName: SmileDirectClub/SmileBuddy-Stable-1
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: Dev Team
          file: app/build/outputs/apk/debug/app-debug.apk
